# -*- coding: utf-8 -*-
"""helloworld

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bie8_wNdNk8pc19Wo5aUTA9fUkkg-aHq
"""

# libraries
import numpy as np
from datetime import datetime


# Hello world function
def hiworld() -> None:
    ''' Imprime el string 'hello world'
    '''
    print('Hello World')

# Rock paper scissors function
def rps() -> None:
    ''' Función interactiva que permite jugar piedra papel o tijera con la maquina,
        continua eternamente hasta que el usuario indica 'n' luego de que la consola
        pregunta 'Play again? (y/n): '.
    '''
    while True:
        play = input('Choose between rock, paper or scissors (r, p, or s): ').lower()
        if play not in ['r', 'p', 's']:
            print("Invalid input. Please enter 'r' for rock, 'p' for paper, or 's' for scissors.")
            continue

        r = np.random.randint(0, 3)
        d = ['rock', 'paper', 'scissors']
        out = d[r]

        if out[0] == play:
            print(f'{out}, it\'s a draw!')
        elif (out == 'rock' and play == 's') or (out == 'scissors' and play == 'p') or (out == 'paper' and play == 'r'):
            print(f'{out}, you lose!')
        else:
            print(f'{out}, you win!')

        again = input('Play again? (y/n): ').lower()
        if again != 'y':
            break

# Function to print the current date
def print_date() -> None:
    ''' Función que imprime la fecha y hora del momento.
    '''
    current_date = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    print(f'Current date and time: {current_date}')

def is_leap_year() -> bool:
    """Function to calculate if it is a leap year."""

    year = int(input("Enter a year to find out if it's a leap year.\n"))
    if year%400 == 0: # Multiples of 400 are leap years.
        leap_year = True
    elif year%100 == 0: # The rest of the multiples of 100 are not leap years.
        leap_year = False
    elif year%4 == 0: # The rest of the multiples of 4 are leap years.
        leap_year = True
    else: # The rest of the years are not leap years.
        leap_year = False

    if leap_year:
        print(str(year), "is a leap year.")
    else:
        print(str(year), "is not a leap year.")


# Example usage
hiworld()
print_date()
is_leap_year()
rps()
