# -*- coding: utf-8 -*-
"""helloworld

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bie8_wNdNk8pc19Wo5aUTA9fUkkg-aHq
"""

#Aaa
import numpy as np
from datetime import datetime


# Hello world function
def hiworld():
    print('Hello World')

# Rock paper scissors function
def rps():
    while True:
        play = input('Choose between rock, paper or scissors (r, p, or s): ').lower()
        if play not in ['r', 'p', 's']:
            print("Invalid input. Please enter 'r' for rock, 'p' for paper, or 's' for scissors.")
            continue

        r = np.random.randint(0, 3)
        d = ['rock', 'paper', 'scissors']
        out = d[r]

        if out[0] == play:
            print(f'{out}, it\'s a draw!')
        elif (out == 'rock' and play == 's') or (out == 'scissors' and play == 'p') or (out == 'paper' and play == 'r'):
            print(f'{out}, you lose!')
        else:
            print(f'{out}, you win!')

        again = input('Play again? (y/n): ').lower()
        if again != 'y':
            break

# Function to print the current date
def print_date():
    current_date = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    print(f'Current date and time: {current_date}')

# Example usage
hiworld()
print_date()
rps()